"""Default delays (seconds) for ADB actions — tune for slower devices if needed."""

KEYBOARD_SWITCH_DELAY = 0.2
TEXT_CLEAR_DELAY = 0.15
TEXT_INPUT_DELAY = 0.3
KEYBOARD_RESTORE_DELAY = 0.15

DEFAULT_TAP_DELAY = 0.15
DEFAULT_SWIPE_DELAY = 0.25
DEFAULT_BACK_DELAY = 0.2
DEFAULT_HOME_DELAY = 0.25
DEFAULT_LAUNCH_DELAY = 0.6
DEFAULT_DOUBLE_TAP_DELAY = 0.15
DOUBLE_TAP_INTERVAL = 0.05
DEFAULT_LONG_PRESS_DELAY = 0.3
